// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhdddrowaxvokelgnmjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZGRkcm93YXh2b2tlbGdubWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDQwNTAsImV4cCI6MjA3NDM4MDA1MH0.SsOYk2Tmgt2o2TfSRi6Rcs2pOAK1oHeHzACkCyx8ZVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});